### ISSUE TITLE
make it python 2.x and 3.x compatible

### ISSUE THREAD

**Issue by dankcushions** [dankcushions/crt-pi-configs#5]
python stinks.. added loads of stuff with 3.x, but 2.x seems very common. i can't imagine anything 3.x in this script couldn't be done with 2.x code instead, so we should make it cross-compatible and get rid of the check.

**Comment by Andrew-H2O** [comment]
The only problem I've found with the new script is that Python2 handles integer division differently.  It treats the output of the division of two integers as an integer.

It can be easily fixed - add the following line to the top of the script (before 'import sys')
`from __future__ import division`

You can then remove the version check from the bottom of the file.  

I've checked, and output from Python2 is identical to output for Python3 when this is done.
