### ISSUE TITLE
Don't use scanline shader on games where the display resolution is not high enough

### ISSUE THREAD

**Issue by dankcushions** [dankcushions/crt-pi-configs#8]
For example, darius at 1080p is 12:3. the scanlines appear like a grey haze. I believe the general rule is that should be a be at least 4 rows (or columns, for vertical games) of pixels per scanline for good results, but we could experiment.

**Comment by Andrew-H2O** [comment]
Addressed in the lastest Pull Request - only apply shaders if the scaling factor is 3 or more.
